[llm]
selected = "together_minimax_m2_7"
[[llm.models]]
enabled = true
name = "openai_gpt_5"
provider = "openai"
readable_name = "OpenAI GPT-5"

[llm.models.params]
model = "gpt-5"
temperature = 1
[[llm.models]]
enabled = true
name = "openai_gpt_5_mini"
provider = "openai"
readable_name = "OpenAI GPT-5 Mini"

[llm.models.params]
model = "gpt-5-mini"
temperature = 1
[[llm.models]]
enabled = true
name = "openai_gpt_4o"
provider = "openai"
readable_name = "OpenAI GPT-4o"

[llm.models.params]
model = "gpt-4o"
temperature = 0
[[llm.models]]
enabled = true
name = "openai_gpt_4o_mini"
provider = "openai"
readable_name = "OpenAI GPT-4o Mini"

[llm.models.params]
model = "gpt-4o-mini"
temperature = 0
[[llm.models]]
enabled = true
name = "anthropic_haiku_35"
provider = "anthropic_bedrock"
readable_name = "Anthropic Claude Haiku 3.5"

[llm.models.params]
model_id = "us.anthropic.claude-3-5-haiku-20241022-v1:0"
temperature = 0
[llm.models.params.model_kwargs]
temperature = 0
[[llm.models]]
enabled = false
name = "together_qwen3-coder-next-fp8"
provider = "together"
readable_name = "Qwen3-Coder-Next-FP8"

[llm.models.params]
max_retries = 2
model = "Qwen/Qwen3-Coder-Next-FP8"
temperature = 0
[[llm.models]]
enabled = false
name = "together_gpt-oss-20b"
provider = "together"
readable_name = "OpenAI GPT-OSS-20B"

[llm.models.params]
max_retries = 2
model = "openai/gpt-oss-20b"
temperature = 0
[[llm.models]]
enabled = true
name = "together_gpt-oss-120b"
provider = "together"
readable_name = "OpenAI GPT-OSS-120B"

[llm.models.params]
max_retries = 2
model = "openai/gpt-oss-120b"
temperature = 0
[[llm.models]]
enabled = true
name = "together_kimi_k2_5"
provider = "together"
readable_name = "Kimi K2.5"

[llm.models.params]
max_retries = 2
model = "moonshotai/Kimi-K2.5"
temperature = 0
[[llm.models]]
enabled = true
name = "together_qwen35_397b"
provider = "together"
readable_name = "Qwen3.5 397B A17B"

[llm.models.params]
max_retries = 2
model = "Qwen/Qwen3.5-397B-A17B"
temperature = 0
[[llm.models]]
enabled = true
name = "together_gemma_4_31b_it"
provider = "together"
readable_name = "Gemma 4 31B IT"

[llm.models.params]
max_retries = 2
model = "google/gemma-4-31B-it"
temperature = 0
[[llm.models]]
enabled = true
name = "together_minimax_m2_7"
provider = "together"
readable_name = "MiniMax M2.7"

[llm.models.params]
max_retries = 2
model = "MiniMaxAI/MiniMax-M2.7"
temperature = 0
[[llm.models]]
enabled = true
name = "llamacpp"
provider = "llamacpp"
readable_name = "Llama.CPP Server"

[llm.models.params]
base_url = "http://localhost:8080/"
temperature = 0

[prompt_engineering]
mode = "disabled"

[prompt_injection_filter]
mode = "aws-bedrock-guardrails"

[delimiter-filtering]
mode = "disabled"

[logging]
verbose = true

[admin]
username = "admin"
password = "mwrisalive"

[server]
session_secret = "CHANGE_ME_RANDOM_LONG"

[limits]
daily_summarize_quota = 500
